version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    command: bundle exec rails server -b 0.0.0.0
